config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'

  resources :users, only: [:show]
  resources :quizzes do
    resources :answers
    resources :games, only: [:new, :create]
  end
  resources :categories
  resources :games do
    member do
      get 'increase_correct_ans', to: "games#increase_correct_ans"
    end
  end

end

app/views/shared/_login.html.erb
<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <% if devise_mapping.rememberable? -%>
        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
    <% end -%>

    <div class="actions">
      <%= f.submit "Log in" %>
    </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Kwiz</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="search"><%= render 'shared/search' %></li>
        <li><%= link_to 'Quizzes', quizzes_path %>  </li>
    <% if Quiz.count != 0 %>
        <li><%= link_to 'Play Random Quiz', quiz_path(Quiz.all.shuffle) %></li>
    <% end %>
    <% if user_signed_in? %>
        <li class="new_quiz"><%= link_to 'Create Quiz', new_quiz_path %></li>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
                <li><%= link_to "Profile Page", user_path(current_user) %></li>
                <li><%= link_to "Account Settings", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        </li>
    <% else %>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Log In<span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= render 'shared/login' %>
          </ul>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Sign Up!<span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= render 'shared/signup' %>
          </ul>
    <% end %>
        <li role="presentation" class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                Categories<span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <% Category.all.each do |category| %>
                    <li class="category"><%= link_to category.name, category %></li>
                <% end %>
                <li role="separator" class="divider"></li>
                <li class="new_category"><%= link_to 'New Category', new_category_path %></li>
              </ul>
            </li>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_quiz_header.html.erb
<table class="table">
  <thead>
      <tr>
        <th>Date Created</th>
        <th>Quiz Name</th>
        <th>Quiz Category</th>
        <th>Number of Plays</th>
        <th>Quiz Creator</th>
      </tr>
  </thead>

app/views/shared/_search.html.erb
<%= form_tag quizzes_path, :method => 'get', :id => 'quiz_search' do %>
    <p class="searcher">
      <%= text_field_tag :search, params[:search], placeholder: "Search quizzes" %>
      <%= submit_tag "Go!", :name => nil %>
    </p>
<% end %>

app/views/shared/_signup.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <%= devise_error_messages! %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up" %>
    </div>
<% end %>